File removal
KSIUJ/mordor pull request #61
Opened 2019-11-08 23:29 UTC by lsereda

2019-11-10 09:50 UTC, SzymonSmykala commented on src/main/resources/templates/preview_code.html
> +            </div>
Why you are pasting the same code in 5 files?

2019-11-10 20:58 UTC, apardyl requested changes

2019-11-10 20:58 UTC, apardyl commented on src/main/kotlin/pl/edu/uj/ii/ksi/mordor/controllers/FilesystemController.kt
> +
Move delete logic to a service

2019-11-10 20:58 UTC, apardyl commented on src/main/resources/application.properties
> +#logging.level.org.springframework.security=DEBUG
Revert.

2019-11-10 20:58 UTC, apardyl commented on src/main/resources/templates/preview_code.html
> +
Revert

2019-11-10 20:58 UTC, apardyl commented on src/main/resources/templates/tree.html
> +    <div class="card-header" sec:authorize="hasRole('ROLE_ACCESS_ADMIN_PANEL')">
Move to a component.

2019-11-10 20:58 UTC, apardyl commented on src/main/resources/templates/preview_too_large.html
> +            <button type="button" class="btn btn-secondary" data-toggle="modal" data-target="#exampleModal"
Move to a component.

2019-11-10 20:58 UTC, apardyl commented on src/main/resources/templates/preview_page.html
> +            <button type="button" class="btn btn-secondary" data-toggle="modal" data-target="#exampleModal"
Move to a component.

2019-11-10 20:58 UTC, apardyl commented on src/main/resources/templates/preview_image.html
> +            <button type="button" class="btn btn-secondary" data-toggle="modal" data-target="#exampleModal"
Move to a component.

2020-01-13 21:04 UTC, kkiermasz commented
@lsereda ping

2020-05-09 18:13 UTC, kkiermasz commented
I close this request due to @lsereda inactivity.

2020-05-09 18:13 UTC, closed without merging